### ISSUE TITLE
single docs page, duplicate the_content()

### ISSUE THREAD

**Issue by tomdowning82** [boonebgorges/buddypress-docs#738]
I have Buddypress 12.0.0 and Buddypress Docs 2.2.0
I have duplicate content on all docs single pages.

My template just renders the_content() (commenting this out removes both content instances).

It looks like from the screenshot, that content is being injected after #buddypress div. (see <p>test</p> after /#buddypress -->

Any clues?

Thanks

<img width="275" alt="Screenshot 2023-12-14 at 17 53 31" src="https://github.com/boonebgorges/buddypress-docs/assets/2786723/200cab30-e3dc-43e0-8be9-41aba7bd924d">

**Comment by dcavins** [comment]
Hi Tom, what theme are you using? Which BuddyPress template pack (legacy or nouveau)? Do you have BP Classic enabled?
Thanks!

**Comment by tomdowning82** [comment]
Thanks for quick response!

<img width="775" alt="Screenshot 2023-12-14 at 18 32 22" src="https://github.com/boonebgorges/buddypress-docs/assets/2786723/05115506-cc41-48de-984d-fc5f18b70981">

**Comment by boonebgorges** [comment]
@dcavins Just a hunch, but I feel like this might have something to do with whether we're returning values here https://github.com/boonebgorges/buddypress-docs/blob/ecc3aed88e27d0a26bf2b1b7d09e12960a6447a3/includes/theme-bridge.php#L255

@tomdowning82 Could you share the name of the theme you're using? It looks like this information is not in your screenshot.

**Comment by dcavins** [comment]
@boonebgorges  That's a good guess. I was feeding that content in in my "work better with wide layouts" branch, else BuddyPress was kicking in (if it didn't see a `#buddypress` element in the passed output).

**Comment by boonebgorges** [comment]
Probably the same issue reported on the wordpress.org support forums: https://wordpress.org/support/topic/duplicated-document/ That site is using the oceanwp theme.

**Comment by tomdowning82** [comment]
> @dcavins Just a hunch, but I feel like this might have something to do with whether we're returning values here
> 
> https://github.com/boonebgorges/buddypress-docs/blob/ecc3aed88e27d0a26bf2b1b7d09e12960a6447a3/includes/theme-bridge.php#L255
> 
> @tomdowning82 Could you share the name of the theme you're using? It looks like this information is not in your screenshot.

Hey, yep its called Thrive, but an old version so probably something to do with that!

**Comment by tomdowning82** [comment]
I've found the culprit, but its in buddypress itself. 
https://github.com/buddypress/buddypress/blob/f4fc5eb186fedbffe82a5f446c8a3b251b2c2d9d/src/bp-core/bp-core-theme-compatibility.php#L749

If I disable this function, the repeated the_content() doesn't get rendered outside of <div id="buddypress>

**Comment by dcavins** [comment]
Good sleuthing! You should be able to temporarily restore the right behavior with a filter like this:
```
add_filter( 'bp_replace_the_content', function( $content ) {
	if ( is_singular( bp_docs_get_post_type_name() ) ) {
		// Passing an empty string will tell BP to take a break.
		$content = '';
	}
	return $content;
} );
```
You can enable the filter by adding it to bp-custom or your theme's functions file, until we figure out the best approach to take in BP Docs. Thanks!

**Comment by boonebgorges** [comment]
Thanks, @tomdowning82 

I've done some digging and have some preliminary findings.

First, for some reason this appears to happen only when running the BuddyPress Legacy template pack, not Nouveau.

Second, I bisected back to 05486efacb107a8a8229fd852029365eb88da003. This, in turn, was a partial revert of a462ba3a8c47fa9cb045355c3ebfcb3384af791e. The latter commit was introduced to address the precise sort of issue raised in this ticket.

The "proper" use of the `bp_replace_the_content` filter has us return the actual buffered template content. I'm unsure why I didn't do this in the past, but I've implemented it for testing in 352a13a. @tomdowning82 and @dcavins Could you have a look? David, I'm especially interested to see whether you can break this across different combinations of template packs and BP versions.

As for why this is a Legacy-only issue, I have no idea and don't want to dig any more :-D

**Comment by dcavins** [comment]
HI Boone, this is part of what I was doing to improve the behavior of BP Docs in block themes, so I suspect that there are unexpected consequences as I found in my branch where I was working on that (that should be solvable), but I do think this is the right way to go.

**Comment by dcavins** [comment]
Hi Boone, I agree that sooner is better. I'm in the middle of something
right now, but will have time around lunch time, so we could still have a
tested fix released today. Thanks!

**Comment by boonebgorges** [comment]
Thanks! I don't think a release *today* is necessary, I just don't want to wait until we unravel the mystery that is block themes, which could be months or decades :-D

**Comment by dcavins** [comment]
Boone, this change does essentially break block themes, at least the archive/directory view, but they are pretty thoroughly broken already, so I'd say let's do this, and I'll follow up with some block theme fixes in the next week or so. Here are my testing results:
<img width="447" alt="image" src="https://github.com/boonebgorges/buddypress-docs/assets/1391994/d9ad2ed1-c27c-47e5-9288-a8a5486db3df">
I did add one change to your branch: We want to not echo the results of `bp_buffer_template_part()` for smoother sailing.

**Comment by Padmon565** [comment]
Hello! Dear Developers! Faced with a similar question!The content in the documents in the plugin is duplicated. My theme is Ureg, officially purchased. The version of BuddyPress Docs is Version 2.2.0, it seems to me that the problem just arose after updating the plugin.
![2](https://github.com/boonebgorges/buddypress-docs/assets/154020021/a4924cce-aec1-477e-b28e-2534aa8e3b09)

I reread the entire discussion thread, tried these solutions, it didn't help me.

**Comment by boonebgorges** [comment]
@Padmon565 Thanks for providing your info. Did you try applying this patch? https://github.com/boonebgorges/buddypress-docs/commit/352a13a0ea347ea5d870d18291146d864e4293a3

**Comment by Padmon565** [comment]
@boonebgorges Thanks for the answer!I am glad to meet the professionals of my field!Please specify in more detail - this code must be completely copied and pasted into function.php themes or in some other php plugin file?
![Code](https://github.com/boonebgorges/buddypress-docs/assets/154020021/681a6a64-d39e-4b32-9a51-bca1d8a521ea)

**Comment by boonebgorges** [comment]
@Padmon565 Do not paste what you've highlighted into any file - it will break your installation. If you can't wait for the 2.2.1 update in a few days, you can patch your installation as follows:

1. Open the file wp-content/plugins/buddypress-docs/includes/theme-bridge.php
2. Replace the entire contents of that file with what you see here https://raw.githubusercontent.com/boonebgorges/buddypress-docs/352a13a0ea347ea5d870d18291146d864e4293a3/includes/theme-bridge.php

If you're less than 100% confident about making such a change, I encourage you to wait for the 2.2.1 release.

**Comment by Padmon565** [comment]
Hello!Please tell me, when will the plugin update you specified be released? Will the update function appear in the wp admin panel or will you need to download the plugin here?

**Comment by boonebgorges** [comment]
@Padmon565 The update will be released when our team is confident that we've got the changes correct. As you can probably tell from this ticket and others linked from this ticket, we are working with a complex set of issues. Thanks for your patience as we enter the holiday season.

**Comment by dcavins** [comment]
Hi Boone,

Thanks for putting together BP Docs 2.2.1 this morning. I hope that it solved many problems for people. 

Thanks again for everything you do in the WP/BP orbit; open source seems like it’s having an identity crisis, but your projects are proof that nice people can get together and build something nice for the common benefit.

Merry Christmas! I’m hoping for a snowy Christmas miracle, but I think that the weather forecast isn’t going to come through for me. At least I’ll get to have some good pizza while I’m up in Moline, IL for the next couple of days.

Thanks!

-David

**Comment by Padmon565** [comment]
Dear developers!Thank you for your work!It is very pleasant and I will not be afraid of this word - to feel proud communicating with professionals in the field of IT.
I updated the plugin - the duplication of content is gone!Everything is OK!

Let me ask 1 more question in this thread, it's not about duplicating content, but for some reason, out of all the documents in the list on the site, only 1 is visible to unregistered users on the site (although there are only 8 of them). At the same time, if you log in under admin access, then all documents are visible. Where are the rights set when creating a document so that they are visible to all users?!

**Comment by dcavins** [comment]
When a document is created, you can set the access to "Anyone" which allows logged-in or not-logged-in users to see the item, "Logged In" which allows only authenticated users to access the doc, or "Doc author only" which does what it says. Check the access settings for the individual docs to be sure they are as permissive as you would like for them to be.

**Comment by Padmon565** [comment]
Hi!Please tell me! didn't find such a setting, how to hide the ability to
see the history of a document?

ср, 27 дек. 2023 г. в 18:30, David Cavins ***@***.***>:
